apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.kubeBench.namespace }}
  name: {{ include "kube-bench.fullname" . }}
  labels:
    {{- include "kube-bench.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "kube-bench.fullname" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["./{{ .Values.kubeBench.command }}"]
            args: [
            "-name","{{ .Values.kubeBench.name}}",
            "-yaml", "{{ .Values.kubeBench.yaml }}",
            "-category", "{{ .Values.kubeBench.category }}",
            "-namespace", "{{ .Values.kubeBench.namespace }}",
            "-kubebenchImg", "{{ .Values.kubeBench.kubebenchImg }}",
            "-kubeconfig", "{{ .Values.kubeBench.kubeconfig }}",
            ]
            {{- with .Values.resources }}
            resources: {{ tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
            {{- with .Values.livenessProbe }}
            livenessProbe: {{ tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
            {{- with .Values.readinessProbe }}
            readinessProbe: {{ tpl (toYaml .) $ | nindent 14 }}
            {{- end }}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
          {{- if .Values.image.pullSecrets.create }}
          imagePullSecrets:
          - name: {{ .Values.image.pullSecrets.name }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName:   {{ include "kube-bench.fullname" . }}
